set_property PACKAGE_PIN H17 [get_ports activar_bomba]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property PACKAGE_PIN L16 [get_ports sensor_lleno]
set_property PACKAGE_PIN M13 [get_ports sensor_vaso]
set_property IOSTANDARD LVCMOS33 [get_ports activar_bomba]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sensor_lleno]
set_property IOSTANDARD LVCMOS33 [get_ports sensor_vaso]

set_property PACKAGE_PIN V11 [get_ports edo_1]
set_property PACKAGE_PIN V12 [get_ports edo_2]
set_property PACKAGE_PIN V14 [get_ports edo_3]
set_property IOSTANDARD LVCMOS33 [get_ports edo_1]
set_property IOSTANDARD LVCMOS33 [get_ports edo_2]
set_property IOSTANDARD LVCMOS33 [get_ports edo_3]
